openapi: 3.0.0
info:
  version: 0.0.1
  title: Pagopa eCommerce user stats service
  description: This microservice handles statistics for payment performed by an authenticated used on eCommerce
  contact:
    name: pagoPA - Touchpoints team
tags:
  - name: user-stats
    description: Api's for tracing and retrieve user statistics
    externalDocs:
      url: TODO
      description: Technical specifications
externalDocs:
  url: https://pagopa.atlassian.net/wiki/spaces/I/pages/492339720/pagoPA+eCommerce+Design+Review
  description: Design review
servers:
  - url: https://${hostname}
paths:
  /user/{userId}/lastPaymentMethodUsed:
    post:
      parameters:
        - name: userId
          in: path
          required: true
          description: User identifier
          schema:
            type: string
            format: uuid

      operationId: saveLastPaymentMethodUsed
      tags:
        - user-stats
      description: Save last payment method used by an user to perform a transaction on eCommerce
      summary: Save last method used
      requestBody:
        $ref: '#/components/requestBodies/UserLastPaymentMethodRequest'
      responses:
        '201':
          description: User last payment method used updated successfully
        '400':
          description: Formally invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '401':
          description: Unauthorized, api key missing or invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '500':
          description: Unexpected error updating user last used payment method
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
    get:
      parameters:
        - name: userId
          in: path
          required: true
          description: User identifier
          schema:
            type: string
            format: uuid
      operationId: getLastPaymentMethodUsed
      tags:
        - user-stats
      description: Retrieve last payment method used by an user to perform a transaction on eCommerce
      summary: Retrieve last method used
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserLastPaymentMethodData'
        '401':
          description: Unauthorized, api key missing or invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '404':
          description: No information found for the input user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '500':
          description: Unexpected error retrieving user last used payment method
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
components:
  schemas:
    ProblemJson:
      description: Body definition for error responses containing failure details
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |-
            An absolute URI that identifies the problem type. When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          default: about:blank
          example: https://example.com/problem/constraint-violation
        title:
          type: string
          description: |-
            A short, summary of the problem type. Written in english and readable
            for engineers (usually not suited for non technical stakeholders and
            not localized); example: Service Unavailable
        status:
          $ref: '#/components/schemas/HttpStatusCode'
        detail:
          type: string
          description: |-
            A human readable explanation specific to this occurrence of the
            problem.
          example: There was an error processing the request
        instance:
          type: string
          format: uri
          description: |-
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
    HttpStatusCode:
      type: integer
      format: int32
      description: |-
        The HTTP status code generated by the origin server for this occurrence
        of the problem.
      minimum: 100
      maximum: 600
      exclusiveMaximum: true
      example: 200
    UserLastPaymentMethodData:
      description: Last usage data for wallet or payment method (guest)
      oneOf:
        - $ref: '#/components/schemas/WalletLastUsageData'
        - $ref: '#/components/schemas/GuestMethodLastUsageData'
      discriminator:
        propertyName: type
        mapping:
          wallet: "#/components/schemas/WalletLastUsageData"
          guest: "#/components/schemas/GuestMethodLastUsageData"
    WalletLastUsageData:
      type: object
      description: Last usage data for wallets.
      properties:
        walletId:
          $ref: '#/components/schemas/WalletId'
        date:
          type: string
          format: date-time
        type:
          $ref: '#/components/schemas/WalletLastUsageType'
      required:
        - walletId
        - date
        - type
    GuestMethodLastUsageData:
      type: object
      description: Last usage data for guest method
      properties:
        paymentMethodId:
          type: string
          format: uuid
          description: eCommerce payment method id associated to this last usage
        date:
          type: string
          format: date-time
        type:
          $ref: '#/components/schemas/GuestMethodLastUsageType'
      required:
        - paymentMethodId
        - date
        - type
    WalletLastUsageType:
      type: string
      description: Discriminant type for last usage of a wallet
      enum:
        - wallet
    GuestMethodLastUsageType:
      type: string
      description: Discriminant type for last usage of a guest (non-wallet) payment method
      enum:
        - guest
    WalletId:
      description: Wallet identifier
      type: string
      format: uuid
  requestBodies:
    UserLastPaymentMethodRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserLastPaymentMethodData'
